name: Docker Image CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:

  build:
 
    runs-on: ubuntu-18.04
 
    steps:
    - uses: actions/checkout@v1

    - name: decide on tag
      run: |
        image_tag=$(echo $GITHUB_REF | sed -e 's/refs\/heads\///g' -e 's/refs\/tags\///g' | sed -e 's/master/latest/g')
        echo "::debug decided on tag ${image_tag}"
        echo "::set-env name=IMAGE_TAG::${image_tag}"

    - name: get ssm version
      run: |
        version=${IMAGE_TAG}
        url=https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/${IMAGE_TAG}/linux_amd64/amazon-ssm-agent.rpm
        curl --output /dev/null --silent --head --fail "$url" || version=$(curl --silent https://api.github.com/repos/aws/amazon-ssm-agent/releases/latest | jq -r .tag_name)
        echo "::set-env name=SSM_VERSION::${version}"

    - name: build image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        docker build --build-arg SSM_VERSION=${SSM_VERSION} --tag ${DOCKER_USERNAME}/aws-ssm-agent:${IMAGE_TAG} .
    
    - name: push image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
        docker push ${DOCKER_USERNAME}/aws-ssm-agent:${IMAGE_TAG}
        docker logout
