name: DockerHub Image CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:

  build:
 
    runs-on: ubuntu-18.04
 
    steps:
    - uses: actions/checkout@v2

    - name: get ssm version
      id: get_ssm
      run: |
        version=$(curl --silent https://api.github.com/repos/aws/amazon-ssm-agent/releases/latest | jq -r .tag_name)
        echo "::debug::get ssm version ${version}"
        echo "::set-output name=version::${version}"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Cache Docker layers
      uses: actions/cache@v2
      id: cache
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        build-args: SSM_VERSION=${{ steps.get_ssm.outputs.version }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/aws-ssm-agent:${{ steps.get_ssm.outputs.version }}
          ${{ secrets.DOCKER_USERNAME }}/aws-ssm-agent:latest
          ghcr.io/${{ github.repository_owner }}/aws-ssm-agent:${{ steps.get_ssm.outputs.version }}
          ghcr.io/${{ github.repository_owner }}/aws-ssm-agent:latest
        push: true

    - name: Tweet about Release
      uses: twwd/twitter-github-action@v1
      with:
        twitter_api_key: ${{ secrets.TWITTER_API_KEY }}
        twitter_api_secret_key: ${{ secrets.TWITTER_API_SECRET_KEY }}
        twitter_access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        twitter_access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        tweet_body: |
            I just released a new version ${{ steps.get_ssm.outputs.version }} of ${{ github.event.repository.name }} 🎉
            Check it out here ${{ github.event.release.html_url }} and download the new Docker image from https://hub.docker.com/r/alexeiled/aws-ssm-agent

    - name: image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

 